easy_admin:
#    resource : '@EasyAdminBundle/Controller/EasyAdminController.php'
    # On définit le nom de l'interface d'administration
    site_name: 'Joseph-Watch e-commerce'
    # On définit l'affichage de l'utilisateur
    user:
        display_name: true
        display_avatar: true
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"
        # Ces lignes définiront notre menu
        menu:
            - { label: 'Produits' }
            - { entity: 'Product', label: 'Produit', icon: 'clock' }
            - { label: 'Utilisateurs' }
            - { entity: 'User', label: 'Utilisateurs', icon: 'user' }
    entities:
        Product:
            # Correspond au fichier Product.php
            class: App\Entity\Product
            # On définit ci-dessous le contenu de la liste qui affichera les articles et les critères de tri
            list:
                fields:
                    - id
                    - name
                    # Le champ ci-dessous affichera l'image de product
                    - { property: 'image', type: 'image', base_path: 'Img-Boutique-e-commerce' }
                    - { property: 'reference', label: 'réf.' }
                    - { property: 'price', label: 'prix'}
                    - { property: 'quantity', label: 'quantité'}
                    - { property: 'description', label: 'description'}
            form:
                fields:
                    - name
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'reference', label: 'réf.' }
                    - { property: 'price', label: 'prix'}
                    - { property: 'quantity', label: 'quantité'}
                    - { property: 'description', label: 'description'}
                    - { property: 'category', label: 'categorie'}


        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                fields:
                    - id
                    - email
                    - { property: 'roles', label: 'Rôles', type: json_array}


            form:
                fields:
                    - property: 'civility'
                      label: 'civility'
                      type: 'choice'
                      type_options:
                          choices:
                              Monsieur : 'M.'
                              Madame: 'Mme'
                              Autre: 'Autre'
                          multiple: false
                          expanded: true
                    - email
                    - password
                    - username
                    - firstname
                    - lastname
                    -
                      property: 'roles'
                      label: 'roles'
                      type: 'choice'
                      type_options:
                          choices:
                              Utilisateur: 'ROLE_USER'
                              Administrateur: 'ROLE_ADMIN'
                          multiple: true
                          expanded: true