vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /Img-Boutique-e-commerce
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public/Img-Boutique-e-commerce'
